### PR TITLE
Add inputmode attribute.

### PR DESCRIPTION
**Pull request by Lasering**

### CODE REVIEW

**Comment by raquo** [comment]
Hey @Lasering, thanks for adding this.

This should actually be a [reflected attribute](https://github.com/raquo/scala-dom-types/#reflected-attributes), defined as

    lazy val inputMode: RA[String, String] = stringReflectedAttr("inputmode", "inputMode")

in `ReflectedHtmlAttrs.scala` instead of `HtmlAttrs.scala`, can you please update the diff?

Note the capitalization, and that the attrs are listed alphabetically in the file.

**Comment by raquo** [comment]
Just fixed a small typo in my last comment, please see it on github.

**Comment by Lasering** [comment]
Done

**Review by raquo — APPROVED** [review]
Awesome, thanks!

**Comment by raquo** [comment]
Just sent 0.15.1 to maven central, will be up there soon.

**Pull request merged**
