### PR TITLE
Update to sjs-dom 2.0.0 final

### PR DESCRIPTION
**Pull request by armanbilge**

### CODE REVIEW

**Comment by raquo** [comment]
Sorry, didn't notice the mentioned PR at first. I see that you plan to release 2.0.0 this week or next week. If you don't need SDT released specifically for 2.0.0-RC1, I'll just wait until 2.0.0 is released.

**Comment by armanbilge** [comment]
I mostly opened this for CI to check everything is good with the RC, is it running? There's no need to publish SDT unless you want test something downstream e.g. laminar.

**Comment by raquo** [comment]
Cool, I dunno what's up with CI, will check later. All it really does on this project is check that it compiles. I release manually.

**Review by ngbinh — APPROVED** [review]

**Comment by raquo** [comment]
@armanbilge This is now released as 0.15.0. Laminar to follow tomorrow. Once again, sorry for the delay, and thanks for all your work on 2.0.0!

**Comment by armanbilge** [comment]
No worries, thank you very much! This will unblock a lot of stuff 😁

**Pull request merged**
