### PR TITLE
New: Add `namespace` param to `SvgAttr`

### PR DESCRIPTION
**Pull request by raquo**
For https://github.com/raquo/Laminar/issues/31

### CODE REVIEW

**Comment by cornerman** [comment]
Good point. In the laminar issue, you mention that e.g. `xlinkHref` needs a namespace which is not `null`. Shouldn't we add it then [here](https://github.com/raquo/scala-dom-types/blob/12446e4cb8782110aea57320c37271e3025ba111/shared/src/main/scala/com/raquo/domtypes/generic/defs/attrs/SvgAttrs.scala#L1444) in this PR?

**Comment by raquo** [comment]
Good catch, yes, that was my intent, will do

--
Nikita

**Comment by doofin** [comment]
@cornerman  is that related to https://github.com/raquo/scala-dom-builder/pull/5 ?

**Comment by fdietze** [comment]
Here are good introductions to xml namespaces and namespace prefixes:
https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course
https://www.w3schools.com/xml/xml_namespaces.asp

While this PR looks good to me, I'm still unsure if baking the `xlink` namespace into `scala-dom-types` makes sense. I'm not experienced enough with xml namespaces to decide this.

**Comment by raquo** [comment]
I think it definitely makes sense from a purely _practical_ standpoint – SVG `xlink` attributes are supposedly popular, and our implementation seems to be the universally accepted way of representing them. I mean, I don't think anyone would _reasonably_ want to associate the `xlink` prefix with a different namespace string, even if technically that's possible in the spec.

I might consider extracting xlink attributes into a separate trait in future releases if a case is made for that, but I don't really see the point right now.

**Pull request merged**
